"""Key and column names"""

KEY_FORECAST_STEPS = "forecast_steps"
KEY_INITIALIZATION_TIMES = "initialization_times"
KEY_URL_BASE = "url_base"
KEY_URL_PATH = "url_path"
KEY_URL_FILE = "url_file"
KEY_VARIABLES = "variables"
KEY_GRIB_PACKAGE_TYPES = "grib_package_types"
KEY_FILE_POSTFIX = "file_postfix"
KEY_INITIALIZATION_DATE_FORMAT = "initialization_date_format"
KEY_LOCAL_FILE_PATHS = "local_file_paths"
KEY_LOCAL_STORE_FILE_PATHS = "local_store_file_paths"
KEY_REMOTE_FILE_PATHS = "remote_file_paths"
KEY_COMPRESSION = "compression"
KEY_FORECAST_STEPS_STR_LEN = "forecast_steps_string_length"
KEY_LEVEL_TYPE = "level_type"
KEY_LIST_INDEX = "list_index"

LOCAL_FILE_POSTFIX = "nc"
