icon_eu:
     air_temperature_2m: single-level
     snow_height: single-level
     max_wind_gust_10m: single-level
     wind_u_10m: single-level
     wind_v_10m: single-level
     dewpoint_2m: single-level
     total_precipitation: single-level
     convective_snow: single-level
     grid_scale_snow: single-level
     convective_rain: single-level
     grid_scale_rain: single-level
     global_horizontal_irradiance: single-level
     direct_normal_irradiance: single-level
     diffuse_horizontal_irradiance: single-level
     mixed_layer_cape: single-level
     pressure_mean_sea_level: single-level
     max_air_temperature_2m: single-level
     min_air_temperature_2m: single-level
     weather_synop_code: single-level
     soil_temperature: single-level
     total_cloud_cover: single-level
     relative_humidity_2m: single-level