name: Codecoverage
on: [push]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: Generate coverage report
      run: |
        pip install -r requirements.txt
        pip install pytest
        pip install pytest-cov
        pytest --cov-report=xml --cov=python_dwd tests/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        file: ./coverage.xml
        flags: pytest
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
