name: Coverage

on:
  push:
    branches: [ main ]
  # Allow invoking this workflow from GitHub UI.
  workflow_dispatch:

jobs:
  run:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.8'

    steps:

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Acquire sources
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install libeccodes0
        pip install --editable=.[test]

    - name: Run tests, with coverage
      run: make test-coverage

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false
