name: Coverage

on:
  push:
    branches: [ main ]
  # Allow invoking this workflow from GitHub UI.
  workflow_dispatch:

jobs:
  run:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    env:
      OS: ${{ matrix.os }}
      PYTHON: ${{ matrix.python-version }}

    steps:

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Acquire sources
      uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ${{ matrix.path }}
        key: ${{ runner.os }}-pip-${{ hashFiles('setup.py', 'requirements-dev.txt') }}
        restore-keys: |
         ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        sudo apt-get install libeccodes0

    - name: Run tests, with coverage
      run: make test-coverage

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v2
      with:
        files: ./coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: false
