name: Coverage
on: [push]
jobs:
  run:
    if: false
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.7'
    steps:
    - uses: actions/checkout@master
    - name: Setup Python
      uses: actions/setup-python@master
      with:
        python-version: 3.7
    - name: build test image 
      run: docker build -t "grib_magic_image" .
    - name: Generate coverage report
      run: docker run -v $(pwd):/app grib_magic_image:latest pytest --cov-report=xml --cov=gribmagic/modules tests/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.7
      with:
        file: ./coverage.xml
        flags: pytest
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
