# Test gribmagic

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Acquire sources
      uses: actions/checkout@v2

    - name: Install dependencies
      run: pip install --requirement requirements.txt

    - name: Acquire test data
      run: wget https://github.com/earthobservations/testdata/raw/main/opendata.dwd.de/weather/nwp/icon-eu/grib/00/t_2m/icon-eu_europe_regular-lat-lon_single-level_2020062300_000_T_2M.grib2.bz2 --directory-prefix tests/modules/download/fixtures/

    - name: Run tests
      run: |
        export BASE_STORE_DIR=.gribmagic-data
        export MODEL_CONFIG=config/model_config.yml
        export MODEL_VARIABLES_MAPPING=config/model_variables_mapping.yml
        export MODEL_VARIABLES_LEVELS_MAPPING=config/model_variables_levels_mapping.yml
        pytest tests
