# Test gribmagic

name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Acquire sources
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get install libeccodes0
        pip install --requirement=requirements.txt --requirement=requirements-dev.txt

    - name: Run tests
      run: make test
